### ISSUE TITLE
자동 거래를 하고 싶은데 API를 제공하실 생각이 있으신가요?

### ISSUE THREAD

**Issue by kifhan** [velopert/bitimulate#4]
안녕하세요. 모의거래 재미있게 하고 있습니다.

현재 저는 bithumb에서 소액 투자를 하면서 경험을 쌓고 있습니다.
bithumb API와 node.js로 자동거래 시스템을 개발하고 있구요.

bitimulate 시뮬레이션에서 자동 거래를 하고 싶은데 API를 제공하실 생각이 있으신가요?

**Comment by velopert** [comment]
안녕하세요. 서비스를 사용해주셔서 감사드립니다 :)
우선 이 프로젝트의 경우엔 한달동안 지켜보고 계속 개발을 할 지 아니면 접어둘지 고민을 하고 있습니다.

사용률이 높아져서 개선을 해도 좋을 것 같다고 판단된다면 할 일 목록에 넣어두도록 하겠습니다.

소중한 의견 감사합니다.
