### ISSUE TITLE
BTC구매했는데 수량이 이상하네요;

### ISSUE THREAD

**Issue by ParkMinKyu** [velopert/bitimulate#5]
시간 | 종류 | 가격 | 거래량 | 상태 |
----- | ----- | ----- | ----- | ----- 
13:01 | 매수 | 14030.000000 | 0.0000000000 | 완료 
13:01 | 매수 | 14030.080193 | 0.2326399087 | 완료
12/6 |  매수 | 13789.817022 | 4.0000000000 | 완료
12/6 | 매수 | 13809.000000 | 3.0000000000 | 완료

거래 내역이 이렇게 되어있는데 현재 지갑에 보유량이 7.2326.... 이렇게 가지고 있어야 정상 아닌가요?

지갑에는

코인  | 변화율 | 이름 | 보유량 | 거래 대기중 | BTC 가치
---- | ---- | ---- | ---- | ---- | ---- |
BTC | +14.31% | Bitcoin | 0.2326399087 | 0.0000000000 | 0.2326399087 

이렇게 나와있네요 그리고 맨위에 거래된 내용도 3개를 구입했는데 0개만 구입한거로 되어있어요 ㅠ

**Comment by velopert** [comment]
안녕하세요! 

거래내역을 조사해보니까, 알트코인들을 구매하셨네요.
비티뮬레이트에서는 BTC 이외의 화폐들을 거래 할 때 비트코인을 사용하여 거래하게 됩니다.

그 때문에 비트코인 보유량이 낮은거일거예요.

지금 전체 보유량을 보니까 6.11 BTC 인것으로 봐서 정상인 것 같습니다.

이용해주셔서 감사합니다 :) 그래도 좀 이상한것같으면 다시 문의주세요.
